assets: /app/assets/
source: /app/content/
destination: /app/public/
site:
  url: "/"
  language: es-es
  language_direction: rtl
  theme: dark
  title: Diario de un crustáceo
  description: Historias, anécdotas y aprendizajes de un desarrollador de Rust
  author: Lorenzo Carbonell <a.k.a atareao>
  avatar: /assets/images/avatar.jpg
  email: correo@servidorlinux.es
