assets: /data/rust/markdownweb/assets/
source: /data/rust/markdownweb/content/
destination: /data/rust/markdownweb/public/
site:
  url: "/"
  language: es
  language_direction: rtl
  theme: dark
  title: Diario de un crustáceo
  description: Historias, anécdotas y aprendizajes de un desarrollador de Rust
  author: Lorenzo Carbonell <a.k.a atareao>
  avatar: /assets/images/
  email: correo@servidorlinux.es
