services:
  markdownweb:
    image: atareao/markdownweb:latest
    container_name: markdownweb
    init: true
    restart: unless-stopped
    volumes:
      - ./assets:/app/assets
      - ./content:/app/content
      - ./config.yml:/app/config.yml
